JWT形式トークンの発行処理の実装
Pockament/auth pull request #1
Opened 2021-12-13 16:29 UTC by laminne

2021-12-14 04:35 UTC, Nanai10a requested changes
これ, 何も考えずに書いたけど変なこと言ってたら無言でrejectしていいのであしからず
あともし作業中だったらDraftにしてください

2021-12-14 04:35 UTC, Nanai10a commented on .gitignore
> +*.key
`\n`

2021-12-14 04:35 UTC, Nanai10a commented on main.go
> +*/
これ個人的に `LICENSE` に書いておく派なんですけどどうなんですかね ( `LICENSE` に書くことでソースコードには書かない, という)

2021-12-14 04:35 UTC, Nanai10a commented on main.go
> +	//routers.Serve()
コメントアウト外そうぜ

2021-12-14 04:35 UTC, Nanai10a commented on routers/main.go
> +}
未実装なのであれば `panic` なりすべきだと思いますが…, これは実装済みの関数？

2021-12-14 04:35 UTC, Nanai10a commented on service/jwt.go
> +	file, err := ioutil.ReadFile("p.pem")
環境変数か, 設定ファイルで指定可能にしませんか

2021-12-14 04:35 UTC, Nanai10a commented on service/jwt.go
> +		}}
`"iss"` は鍵のE-mailを使ってほしいのと, 他ハードコードされた部分( `"iss"` , `"sub"` , `"aud"` , `"dom"` , `"jti"` )は今後の実装で直すということで良いのだろうか
もし実装例 / テストであれば `*_test.go` なりに移したほうが良いのでは？

2021-12-14 15:22 UTC, laminne commented on main.go
> +*/
LICENSEとは別にmainファイルにコピーライトを書くのは私の癖です

2021-12-14 15:22 UTC, laminne commented on service/jwt.go
> +		}}
JWT発行する鍵ってEmail指定できたっけ

2021-12-14 17:52 UTC, Nanai10a commented on service/jwt.go
> +		}}
PGP…？のそれってE-mailとかの情報込みじゃないんか 適当言ったので流してもらって結構です (分からない)

2021-12-15 07:07 UTC, laminne commented on service/jwt.go
> +		}}
鍵ってJWTの署名用の鍵？それとも別？

2021-12-15 07:32 UTC, Nanai10a commented on service/jwt.go
> +		}}
署名用です.

2021-12-15 07:33 UTC, laminne commented on service/jwt.go
> +		}}
Golangで吐く鍵だからEmailは追加できないと思います

2021-12-15 07:34 UTC, Nanai10a commented on service/jwt.go
> +		}}
じゃあ…発行者及び責任者の連絡先をそこへ記載するということで.

2021-12-15 07:35 UTC, laminne commented on service/jwt.go
> +		}}
環境変数から読み出すように変更しておきますね

2021-12-15 14:10 UTC, laminne commented
修正 Done

2021-12-15 16:22 UTC, Nanai10a requested changes
ま〜た何か言ってるよ此の人…(ごめんなさい

2021-12-15 16:22 UTC, Nanai10a commented on service/jwt.go
> +			ExpiresAt: jwt.NewNumericDate(time.Now().Add(24 * time.Hour)),
良い忘れていました, こちらは `"sub"` に応じて変更するので…と言っても, 一対一で完全に一致している必要はないので, `option` に追記をしてください.

2021-12-15 16:22 UTC, Nanai10a commented on service/jwt.go
> +type JWTOption struct {
`*Option` だとnullableで構成されている, "あってもなくても良い"ように感じられるのですが… `*Data` や `*Info` などがより適切と考えます.

2021-12-15 16:28 UTC, Nanai10a commented on service/jwt.go
> +			ExpiresAt: jwt.NewNumericDate(time.Now().Add(24 * time.Hour)),
`time.Hour` が有りますね, こちらの勘違いでした. 申し訳無い…

2021-12-15 16:30 UTC, Nanai10a approved these changes
お疲れ様でした. 🍵

2021-12-15 16:30 UTC, merged